# -*- coding: utf-8 -*-
"""Customer Segmentation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o-s1n5G1pP8F5cLsRCqzIy2HGVlO6NGA
"""

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.cluster import KMeans

customer_data=pd.read_csv("/content/Mall_Customers.csv")

customer_data.isnull().sum()

customer_data.head()

x=customer_data.drop(columns={"CustomerID","Gender","Age"},axis=1).values

print(x)

wcss=[]

for i in range(1,10):
  kmeans=KMeans(n_clusters=i,init="k-means++",random_state=47)
  kmeans.fit(x)

  wcss.append(kmeans.inertia_)

sns.set()
plt.plot(range(1,10),wcss)
plt.title("Elbow Plot")
plt.xlabel("No. of clusters")
plt.ylabel("WCSS")
plt.show

kmeans=KMeans(n_clusters=5,init="k-means++", random_state=2)
y=kmeans.fit_predict(x)
print(y)

plt.figure(figsize=(9,9))
plt.scatter(x[y==0,0],x[y==0,1],s=50,c='green',label="Cluster1")
plt.scatter(x[y==1,0],x[y==1,1],s=50,c='red',label="Cluster2")
plt.scatter(x[y==2,0],x[y==2,1],s=50,c='blue',label="Cluster3")
plt.scatter(x[y==3,0],x[y==3,1],s=50,c='violet',label="Cluster4")
plt.scatter(x[y==4,0],x[y==4,1],s=50,c='black',label="Cluster5")
plt.scatter(x[y==5,0],x[y==5,1],s=50,c='brown',label="Cluster6")
plt.scatter(kmeans.cluster_centers_[:,0],kmeans.cluster_centers_[:,1],s=100,c='cyan',label='centroids')
plt.title("Customer Groups")
plt.xlabel("Annual Income")
plt.ylabel("Spending Score")
plt.show

"""From Above Scatter Plot We have segregated various customers into different groups.

"""

